name: BaGet .nupkg
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build and Push
      run: |
        export vers=0.0.2-alpha-$(date +"%y%j%H%M")
        
